# Generated by Django 5.2.16 on 2026-07-13 06:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('increments', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='IncrementFeedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('suggestion', models.CharField(choices=[('SUGGEST', 'Yeah! I suggest increment for this employee'), ('NEUTRAL', 'My suggestion is neutral, this is working normal'), ('NOT_SUGGEST', "No, I don't suggest — not working hard")], max_length=15)),
                ('description', models.TextField(blank=True, help_text='Why do you think so?')),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('increment_request', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='feedback', to='increments.incrementrequest')),
                ('manager', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='increment_feedbacks_given', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
