# Generated by Django 5.2.16 on 2026-07-13 06:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('increments', '0002_incrementfeedback'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='incrementrequest',
            name='feedback_manager',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='increments_feedback_requested', to=settings.AUTH_USER_MODEL),
        ),
    ]
