# Generated by Django 5.2.16 on 2026-07-13 07:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('increments', '0003_incrementrequest_feedback_manager'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='IncrementCycleSkip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('anniversary_date', models.DateField()),
                ('skipped_at', models.DateTimeField(auto_now_add=True)),
                ('skipped_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='increment_skips_made', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='increment_skips', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'anniversary_date')},
            },
        ),
    ]
