# Generated by Django 5.2.16 on 2026-07-13 07:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0003_alter_employeedocument_doc_type_resignationrequest'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resignationrequest',
            name='proposed_exit_date',
        ),
        migrations.AddField(
            model_name='resignationrequest',
            name='employee_replied_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='resignationrequest',
            name='employee_reply',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='resignationrequest',
            name='exit_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='resignationrequest',
            name='hr_message',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='resignationrequest',
            name='hr_message_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='resignationrequest',
            name='hr_message_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resignation_offers_sent', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='resignationrequest',
            name='notice_period_days',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='resignationrequest',
            name='reason',
            field=models.TextField(help_text='Reason for resigning.'),
        ),
        migrations.AlterField(
            model_name='resignationrequest',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending HR Review'), ('NEGOTIATING', 'HR Sent an Offer'), ('ACCEPTED', 'Approved'), ('REJECTED', 'Rejected'), ('WITHDRAWN', 'Withdrawn (Offer Accepted)')], default='PENDING', max_length=12),
        ),
    ]
