# Generated by Django 5.2.16 on 2026-07-20 10:23

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0004_remove_resignationrequest_proposed_exit_date_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='employeeprofile',
            name='blood_group',
            field=models.CharField(blank=True, choices=[('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('AB+', 'AB+'), ('AB-', 'AB-'), ('O+', 'O+'), ('O-', 'O-')], max_length=5),
        ),
        migrations.AddField(
            model_name='employeeprofile',
            name='current_company_experience',
            field=models.CharField(blank=True, help_text='e.g. 1.5 years', max_length=100),
        ),
        migrations.AddField(
            model_name='employeeprofile',
            name='employment_status',
            field=models.CharField(choices=[('PERMANENT', 'Permanent'), ('PROBATION', 'Probation Period')], default='PROBATION', max_length=10),
        ),
        migrations.AddField(
            model_name='employeeprofile',
            name='enrollment_id',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='employeeprofile',
            name='esi_number',
            field=models.CharField(blank=True, max_length=30, verbose_name='ESI Number'),
        ),
        migrations.AddField(
            model_name='employeeprofile',
            name='gender',
            field=models.CharField(blank=True, choices=[('MALE', 'Male'), ('FEMALE', 'Female')], max_length=10),
        ),
        migrations.AddField(
            model_name='employeeprofile',
            name='id_card_received',
            field=models.BooleanField(default=False, verbose_name='ID Card Received'),
        ),
        migrations.AddField(
            model_name='employeeprofile',
            name='is_pf_applicable',
            field=models.BooleanField(default=True, verbose_name='PF Applicable'),
        ),
        migrations.AddField(
            model_name='employeeprofile',
            name='marital_status',
            field=models.CharField(blank=True, choices=[('SINGLE', 'Single'), ('MARRIED', 'Married'), ('OTHER', 'Other')], max_length=10),
        ),
        migrations.AddField(
            model_name='employeeprofile',
            name='old_joining_date',
            field=models.DateField(blank=True, help_text='Original joining date, preserved automatically if this employee resigned and later rejoined.', null=True),
        ),
        migrations.AddField(
            model_name='employeeprofile',
            name='previous_experience',
            field=models.CharField(blank=True, help_text='e.g. 2 years at XYZ Corp', max_length=200),
        ),
        migrations.AddField(
            model_name='employeeprofile',
            name='qualification',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='employeeprofile',
            name='reference1_contact',
            field=models.CharField(blank=True, max_length=10, validators=[django.core.validators.RegexValidator(message='Enter a valid 10-digit phone number (no spaces, no country code).', regex='^[0-9]{10}$')], verbose_name='Reference 1 Contact'),
        ),
        migrations.AddField(
            model_name='employeeprofile',
            name='reference1_name',
            field=models.CharField(blank=True, max_length=150, verbose_name='Reference 1 Name'),
        ),
        migrations.AddField(
            model_name='employeeprofile',
            name='reference1_type',
            field=models.CharField(blank=True, choices=[('FACULTY', 'College Faculty'), ('COMPANY', 'Previous Company')], max_length=10, verbose_name='Reference 1 Type'),
        ),
        migrations.AddField(
            model_name='employeeprofile',
            name='reference2_contact',
            field=models.CharField(blank=True, max_length=10, validators=[django.core.validators.RegexValidator(message='Enter a valid 10-digit phone number (no spaces, no country code).', regex='^[0-9]{10}$')], verbose_name='Reference 2 Contact'),
        ),
        migrations.AddField(
            model_name='employeeprofile',
            name='reference2_name',
            field=models.CharField(blank=True, max_length=150, verbose_name='Reference 2 Name (Relative)'),
        ),
        migrations.AddField(
            model_name='employeeprofile',
            name='reference2_relation',
            field=models.CharField(blank=True, max_length=100, verbose_name='Reference 2 Relation'),
        ),
        migrations.AddField(
            model_name='employeeprofile',
            name='referred_by_enrollment_id',
            field=models.CharField(blank=True, max_length=20, verbose_name='Referred By (Enrollment No.)'),
        ),
        migrations.AddField(
            model_name='employeeprofile',
            name='referred_by_name',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='employeeprofile',
            name='shift',
            field=models.CharField(blank=True, choices=[('GENERAL', 'General Shift'), ('FIRST', 'First Shift'), ('SECOND', 'Second Shift'), ('NIGHT', 'Night Shift')], max_length=10),
        ),
        migrations.AddField(
            model_name='employeeprofile',
            name='uan_pf_number',
            field=models.CharField(blank=True, max_length=30, verbose_name='UAN / PF Number'),
        ),
        migrations.AddField(
            model_name='employeeprofile',
            name='work_type',
            field=models.CharField(blank=True, choices=[('WFH', 'Work From Home'), ('OFFICE', 'In Office')], max_length=10),
        ),
        migrations.CreateModel(
            name='BankDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_holder_name', models.CharField(blank=True, max_length=150)),
                ('account_number', models.CharField(blank=True, max_length=18, validators=[django.core.validators.RegexValidator(message='Bank account number must be 9 to 18 digits.', regex='^[0-9]{9,18}$')])),
                ('ifsc_code', models.CharField(blank=True, max_length=11, validators=[django.core.validators.RegexValidator(message='Enter a valid IFSC code, e.g. HDFC0001234.', regex='^[A-Za-z]{4}0[A-Za-z0-9]{6}$')])),
                ('bank_name', models.CharField(blank=True, max_length=150)),
                ('branch_name', models.CharField(blank=True, max_length=150)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='bank_detail', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
