# Generated by Django 6.0.7 on 2026-07-24 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0005_employeeprofile_blood_group_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeeprofile',
            name='employment_status',
            field=models.CharField(blank=True, choices=[('PERMANENT', 'Permanent'), ('PROBATION', 'Probation Period')], default='PROBATION', max_length=10),
        ),
    ]
