# Generated by Django 5.2.16 on 2026-07-13 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_department_manager'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='phone_country_code',
            field=models.CharField(choices=[('+91', 'India (+91)'), ('+1', 'USA / Canada (+1)'), ('+44', 'UK (+44)'), ('+61', 'Australia (+61)'), ('+971', 'UAE (+971)'), ('+65', 'Singapore (+65)'), ('+49', 'Germany (+49)'), ('+33', 'France (+33)'), ('+81', 'Japan (+81)'), ('+86', 'China (+86)'), ('+92', 'Pakistan (+92)'), ('+880', 'Bangladesh (+880)'), ('+94', 'Sri Lanka (+94)'), ('+966', 'Saudi Arabia (+966)'), ('+974', 'Qatar (+974)')], default='+91', max_length=5),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
