# Generated by Django 6.0.7 on 2026-07-21 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_seed_branches'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='accessible_branches',
            field=models.ManyToManyField(blank=True, help_text='Branches this HR user can view/manage. Ignored for Admin — Admin always has access to every branch.', related_name='hr_admins', to='core.branch'),
        ),
    ]
