# Generated by Django 5.2.16 on 2026-07-11 06:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leaves', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='leaverequest',
            name='reviewed_by',
        ),
        migrations.AddField(
            model_name='leaverequest',
            name='hr_reviewed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='leaverequest',
            name='manager_reviewed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='leaverequest',
            name='reviewed_by_hr',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='leaves_hr_reviewed', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='leaverequest',
            name='reviewed_by_manager',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='leaves_manager_reviewed', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='leaverequest',
            name='status',
            field=models.CharField(choices=[('PENDING_MANAGER', 'Pending Manager Approval'), ('PENDING_HR', 'Pending HR Approval'), ('MANAGER_REJECTED', 'Rejected by Manager'), ('HR_APPROVED', 'Approved'), ('HR_REJECTED', 'Rejected by HR')], default='PENDING_MANAGER', max_length=20),
        ),
    ]
