# Generated by Django 5.2.16 on 2026-07-11 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leaves', '0002_remove_leaverequest_reviewed_by_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leaverequest',
            name='status',
            field=models.CharField(choices=[('PENDING_MANAGER', 'Pending Manager Approval'), ('PENDING_HR', 'Pending HR Approval'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='PENDING_MANAGER', max_length=20),
        ),
    ]
