# Generated by Django 5.2.16 on 2026-07-15 08:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leaves', '0003_alter_leaverequest_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='leaverequest',
            options={'ordering': ['-applied_at']},
        ),
        migrations.AddField(
            model_name='leaverequest',
            name='from_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='leaverequest',
            name='num_hours',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True),
        ),
        migrations.AddField(
            model_name='leaverequest',
            name='permission_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='leaverequest',
            name='request_type',
            field=models.CharField(choices=[('PERMISSION', 'Permission'), ('LEAVE', 'Leave')], default='PERMISSION', max_length=10),
        ),
        migrations.AddField(
            model_name='leaverequest',
            name='target_hr',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='leaves_targeted_as_hr', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='leaverequest',
            name='to_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='leaverequest',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='leaverequest',
            name='leave_type',
            field=models.CharField(blank=True, choices=[('CL', 'Casual Leave'), ('EL', 'Earned Leave'), ('SICK', 'Sick Leave')], max_length=10),
        ),
        migrations.AlterField(
            model_name='leaverequest',
            name='start_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='leaverequest',
            name='status',
            field=models.CharField(choices=[('PENDING_MANAGER', 'Pending Manager Approval'), ('PENDING_HR', 'Pending HR Approval'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('HR_REJECTED_PENDING_MANAGER', 'HR Declined - Awaiting Manager')], default='PENDING_MANAGER', max_length=30),
        ),
        migrations.CreateModel(
            name='LeaveNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.CharField(max_length=255)),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('leave_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='leaves.leaverequest')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leave_notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
