# Generated by Django 5.2.16 on 2026-07-17 04:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0002_attendancerecord_is_night_duty_and_more'),
        ('projects', '0004_project_completed_at_project_completed_by_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OvertimePermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('permission_type', models.CharField(choices=[('OVERTIME', 'Overtime (extra hours on a working day)'), ('SUNDAY', 'Sunday Work'), ('BOTH', 'Overtime + Sunday Work')], default='BOTH', max_length=10)),
                ('notes', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('authorized_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='overtime_permissions_granted', to=settings.AUTH_USER_MODEL)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='overtime_permissions', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='overtime_permissions', to='projects.project')),
            ],
            options={
                'ordering': ['-date'],
                'unique_together': {('employee', 'project', 'date')},
            },
        ),
    ]
