# Generated by Django 5.2.16 on 2026-07-20 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0003_overtimepermission'),
    ]

    operations = [
        migrations.AddField(
            model_name='monthlyattendancesheet',
            name='cl_quota_override',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='monthlyattendancesheet',
            name='ph_sunday_override',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
